//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetScummTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotNetScummTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanClickNonZeroHotSpot {
            get {
                object obj = ResourceManager.GetObject("CanClickNonZeroHotSpot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanMoveMouse {
            get {
                object obj = ResourceManager.GetObject("CanMoveMouse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanMoveMouseFarBottom {
            get {
                object obj = ResourceManager.GetObject("CanMoveMouseFarBottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanMoveMouseFarLeft {
            get {
                object obj = ResourceManager.GetObject("CanMoveMouseFarLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanMoveMouseFarRight {
            get {
                object obj = ResourceManager.GetObject("CanMoveMouseFarRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanMoveMouseFarTop {
            get {
                object obj = ResourceManager.GetObject("CanMoveMouseFarTop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanMoveMouseMultipleTimes {
            get {
                object obj = ResourceManager.GetObject("CanMoveMouseMultipleTimes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanMoveMousePaletteDisabled {
            get {
                object obj = ResourceManager.GetObject("CanMoveMousePaletteDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanRestore {
            get {
                object obj = ResourceManager.GetObject("CanRestore", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanSendBackspace {
            get {
                object obj = ResourceManager.GetObject("CanSendBackspace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanSendDownArrow {
            get {
                object obj = ResourceManager.GetObject("CanSendDownArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanSendEnter {
            get {
                object obj = ResourceManager.GetObject("CanSendEnter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanSendEsc {
            get {
                object obj = ResourceManager.GetObject("CanSendEsc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanSendF1 {
            get {
                object obj = ResourceManager.GetObject("CanSendF1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanSendF2 {
            get {
                object obj = ResourceManager.GetObject("CanSendF2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanSendF4 {
            get {
                object obj = ResourceManager.GetObject("CanSendF4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanSendLeft {
            get {
                object obj = ResourceManager.GetObject("CanSendLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanSendRight {
            get {
                object obj = ResourceManager.GetObject("CanSendRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanSendString {
            get {
                object obj = ResourceManager.GetObject("CanSendString", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanSendTab {
            get {
                object obj = ResourceManager.GetObject("CanSendTab", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanSendUp {
            get {
                object obj = ResourceManager.GetObject("CanSendUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanStart {
            get {
                object obj = ResourceManager.GetObject("CanStart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CursorCropsFarRight {
            get {
                object obj = ResourceManager.GetObject("CursorCropsFarRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DoesDisplayBlackFirstFrame {
            get {
                object obj = ResourceManager.GetObject("DoesDisplayBlackFirstFrame", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ***.G,**g²³|.Õq:õc=@RÅ¢í&lt;G¸|ÞÃÈïßñOdNÓØD&lt;§µa///wÃ;½Ç±&quot;¿Édzïl¡·PI­í)ÌQ)c)³m4Öt¥ØÅ¹)8t¡÷âêçjc{þo|qÕ^ÆÝÒûJ­äüïÔHN=JÐ%ÂÀi·}¿»M¡ÒäO»üÇ¦¥D°.´î&apos;ãÖzGò õíô#îwºyJ[aÂR$=@êt&lt;«EÔÕcNYW ÒZ|WØÇº=}Ë#íA¦N5	®P¿Õú-Öeë![@ûY×Çþ¬_ì9///C¬ÙcÙÃjúK&quot;iê½6L=M+NÞÑò3}U¥ëàÅAeWìö¹t2(+nzS|ÑðµUïøÆÔ¸ä///áhM3Öâ_ä4ÆI]A0~rdûß§&amp;3Ùhã$1ãÍ©Bqª=}=}«¸I.Õtkw­KCFa¨Ã ¿E0ó§°×Ü~`a÷åz?ÜIÓ®mdîDl«9jWÑJ///Kö©Põ¸¾/C:çüØÎÆ¨cZ«©o-rF1TòþõåÃãºP¢qJDo Å5@ÞÙ}-.j [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KingsQuest4OnMountain {
            get {
                return ResourceManager.GetString("KingsQuest4OnMountain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ***.¦k***g²³{$Ó Ë qQÙ¼is;©æûÀ3=}:©sèµäX©ÁT=}M3ZÄjL@[ÆgywÚ1É]~_+IR¬[v&amp;§¨Èîßp.òOßf&lt;uVy///üþEáÈ£Eð³ûµÊY=M^`ªñjÖÆ/¬Pà_Ö$©÷-Þ:!m$KIÍäïMKWÝ8-^L#¶Ëe{ ¹VòÏ,ì÷N¸L=@p¯³°ðMµHø½Ã¥ÚÞ¶ª  ÿèÔ§UæÑ§·NI9±®=@³ÉûÝ§ÇJÌÜ|*¦«AEüB8ÝCØ`Ú=@Ëj~~UgÆ¢ñ×3sBÇV B×zë=})tåÝ4¥Ñ·Ò²#z£ãÞËä®i@W:5Â)àæx0äeDófÚSÑiíå½8Úu}ûTõH#&amp;k///)=n½JÜvò7Á0G|Â¹Àûý{öO4~ø¦H&gt;&lt;~åu&amp;ÝCâñ &apos;ÚÃîå&lt;n&amp;7ð¬]ÿèA*nQäA1bÏ·Ý;Áàú«ÿh/ëvKGm¹¼S}qGÁnÕW©?fÊv6Yÿ=J [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Kq3CanRestore {
            get {
                return ResourceManager.GetString("Kq3CanRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Thumbnail {
            get {
                object obj = ResourceManager.GetObject("Thumbnail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
