//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetScummTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotNetScummTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanClickButtonRequiringLongMousePress {
            get {
                object obj = ResourceManager.GetObject("CanClickButtonRequiringLongMousePress", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanClickNonZeroHotSpot {
            get {
                object obj = ResourceManager.GetObject("CanClickNonZeroHotSpot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanMoveMouse {
            get {
                object obj = ResourceManager.GetObject("CanMoveMouse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanMoveMouseFarBottom {
            get {
                object obj = ResourceManager.GetObject("CanMoveMouseFarBottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanMoveMouseFarLeft {
            get {
                object obj = ResourceManager.GetObject("CanMoveMouseFarLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanMoveMouseFarRight {
            get {
                object obj = ResourceManager.GetObject("CanMoveMouseFarRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanMoveMouseFarTop {
            get {
                object obj = ResourceManager.GetObject("CanMoveMouseFarTop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanMoveMouseMultipleTimes {
            get {
                object obj = ResourceManager.GetObject("CanMoveMouseMultipleTimes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanMoveMousePaletteDisabled {
            get {
                object obj = ResourceManager.GetObject("CanMoveMousePaletteDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanRestore {
            get {
                object obj = ResourceManager.GetObject("CanRestore", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanRunGameRequiringLockScreen {
            get {
                object obj = ResourceManager.GetObject("CanRunGameRequiringLockScreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanRunGamesRequiringReentrantMutexes {
            get {
                object obj = ResourceManager.GetObject("CanRunGamesRequiringReentrantMutexes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanRunGamesWithMusicTimer {
            get {
                object obj = ResourceManager.GetObject("CanRunGamesWithMusicTimer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanSendBackspace {
            get {
                object obj = ResourceManager.GetObject("CanSendBackspace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanSendDownArrow {
            get {
                object obj = ResourceManager.GetObject("CanSendDownArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanSendEnter {
            get {
                object obj = ResourceManager.GetObject("CanSendEnter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanSendEsc {
            get {
                object obj = ResourceManager.GetObject("CanSendEsc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanSendF1 {
            get {
                object obj = ResourceManager.GetObject("CanSendF1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanSendF2 {
            get {
                object obj = ResourceManager.GetObject("CanSendF2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanSendF4 {
            get {
                object obj = ResourceManager.GetObject("CanSendF4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanSendLeft {
            get {
                object obj = ResourceManager.GetObject("CanSendLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanSendRight {
            get {
                object obj = ResourceManager.GetObject("CanSendRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanSendString {
            get {
                object obj = ResourceManager.GetObject("CanSendString", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanSendTab {
            get {
                object obj = ResourceManager.GetObject("CanSendTab", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanSendUp {
            get {
                object obj = ResourceManager.GetObject("CanSendUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanStart {
            get {
                object obj = ResourceManager.GetObject("CanStart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanStartKq5 {
            get {
                object obj = ResourceManager.GetObject("CanStartKq5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CursorCropsFarRight {
            get {
                object obj = ResourceManager.GetObject("CursorCropsFarRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DoesDisplayBlackFirstFrame {
            get {
                object obj = ResourceManager.GetObject("DoesDisplayBlackFirstFrame", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XQAAAAQYAQMAAD2IiWdSBKtHEMs51iibeMMSYx1vjlLhtIoRSxXka15GpogVVBDl9sByoiSYt4aZatDrXGzdtM40E1sB7NERkOmqgpfHnzDf9GGQ8qxUX3hlF44QvAF8Lt9BzyjaB9C2wTqNH21ZIlhxBrbYWlcpjNhUncTHAeMyf/yiZPVtM4EIEoKXl2IrbMzy6RvUoGvOsgiinmrKxCXMsPgIyIizCmmtTxYAeEEh7BPYrumgttJ+SBUSPMxhvs6CExi++odUwS84Oe0l1oDiRjbz7YkH1xE2OksM96hXlCiB3kewwJd6ZCFsTdcNmiy0g3Vs+ZYPQsDldHm5KHOCaHQHZ/OpySTlLGI3kRuU4uaF43ds3HgOcgTK5eMp1DqYX8uf5YCIEKg30E7ei5iF3cP9bdqNzoSgMX84kak/hL5m0T1LD9+jXIAWjnVpRIHLD0aPt3faTolY8PCVqr2ThSCmIfX5w96f62vied5x/bLzEUO+H/x0lAfMZRL8 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KingsQuest4OnMountain {
            get {
                return ResourceManager.GetString("KingsQuest4OnMountain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XQAAAAStRwEAAD2IiWdR+qn2aKH22kcnaa+S2T9JEWJ/vNGWCWIT8BB/YVrmSb7Zi7oupeh0WCufzWl07Zby/uAdwZFoO7mdMJF7Mjv2Oy8TzOC+ZJVMcvFxYxJOUTfx08smYvxuaegjrZmOAjeTqFAn3dm5nFpp59Gb16Ovaec4NC0nPlJwRxZHzX6GpnmIyZkXr6U+xaZ/IPBxJh1hVIfTomRS9iTeeEADpx0Q+SeEkWExMPY3qCLs1ophJ+LwK2+5W6OrIPZFyNOjvJXZ5cRsFDMryeEq2DC2eIYADLAMLjk93JxtJriihKFQjBQWSLHfh9biIQongdb3gPCw93t9ngX3K8MX3n6HUS9XG5LZk9q8dfz8XmLL2Jna7rmD1weqDkyIocyBoqFis8loacVFvkeOeg3vL0QGoEni2Oy9pYo5arLOqU+eyqJVloBNE46DwevXidNOz5/IfdS4OOpTLUeWumX3XHucwzx2lIYZrHAvwlbcjQJp8b6eT1Qr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Kq3CanRestore {
            get {
                return ResourceManager.GetString("Kq3CanRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XQAAAARgdAIAAD2IiWdSDBzswLVpPG0N2Zj4vuZ/fzZYLMHDxu9sNeJLdQlqCOrOt2MKrNxfzVxSL9MUpFVobpzK15buVwqPccA83DCIeqpmui7fCFtZRrKzhzTUbRgDPo42tOcczEsvS+eWJNN4Grj1rFNmf6VIC/AmkEFp6HOFoauJGC4srP2N0Tqrw1YouxqZtw5yfgYDF+cs/hpD+NzUx/RKv0PrJlJ3KMe8UHNr/zcwQ5jsa1gjJpxYI1OYphaf+GsR/LuqWr+akKU4J7+/M5GuNwy/CdfX5n1/a/iWaTwrkFifAho49omZ/K/hQOXGUgd9BySlteHzEf8ySiXWOXh9JbssSlM5gu/Wx88bPWfSC/nQUKLBE4N/shLszgK6EjIYYwLnA7e5o1KC2wSW99On3pRnvQBTlFbwbpGr+Rw47dphH3kO1JEztTvjiRyWtxbenZ9IjxdrvUAP3JcjHIKdndX0cBt89XheEgr1/p+nAEOfJhhGvmJnKD/b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Kq5CanStart {
            get {
                return ResourceManager.GetString("Kq5CanStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Thumbnail {
            get {
                object obj = ResourceManager.GetObject("Thumbnail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
