//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.4
//
// <auto-generated>
//
// Generated from file `ScummWebServer.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

/* eslint-disable */
/* jshint ignore: start */

(function(module, require, exports)
{
    const Ice = require("ice").Ice;
    const _ModuleRegistry = Ice._ModuleRegistry;
    const Slice = Ice.Slice;

    let ScummWebsServerVMSlices = _ModuleRegistry.module("ScummWebsServerVMSlices");

    Slice.defineDictionary(ScummWebsServerVMSlices, "GameStorage", "GameStorageHelper", "Ice.StringHelper", "Ice.StringHelper", false, undefined, undefined);

    const iceC_ScummWebsServerVMSlices_ScummWebServerClient_ids = [
        "::Ice::Object",
        "::ScummWebsServerVMSlices::ScummWebServerClient"
    ];

    ScummWebsServerVMSlices.ScummWebServerClient = class extends Ice.Object
    {
    };

    ScummWebsServerVMSlices.ScummWebServerClientPrx = class extends Ice.ObjectPrx
    {
    };

    Slice.defineOperations(ScummWebsServerVMSlices.ScummWebServerClient, ScummWebsServerVMSlices.ScummWebServerClientPrx, iceC_ScummWebsServerVMSlices_ScummWebServerClient_ids, 1,
    {
        "SaveGame": [, , , , [1], [[7]], , , , ]
    });

    const iceC_ScummWebsServerVMSlices_ScummWebServer_ids = [
        "::Ice::Object",
        "::ScummWebsServerVMSlices::ScummWebServer"
    ];

    ScummWebsServerVMSlices.ScummWebServer = class extends Ice.Object
    {
    };

    ScummWebsServerVMSlices.ScummWebServerPrx = class extends Ice.ObjectPrx
    {
    };

    Slice.defineOperations(ScummWebsServerVMSlices.ScummWebServer, ScummWebsServerVMSlices.ScummWebServerPrx, iceC_ScummWebsServerVMSlices_ScummWebServer_ids, 1,
    {
        "addClient": [, , , , , [["ScummWebsServerVMSlices.ScummWebServerClientPrx"], [7]], , , , ],
        "Init": [, , , , , [[7]], , , , ],
        "RunGame": [, , , , , [[7], [7], [7]], , , , ],
        "Quit": [, , , , , [[7]], , , , ],
        "GetControlKeys": [, , , , [7], , , , , ]
    });
    exports.ScummWebsServerVMSlices = ScummWebsServerVMSlices;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require :
 (typeof WorkerGlobalScope !== "undefined" && self instanceof WorkerGlobalScope) ? self.Ice._require : window.Ice._require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports :
 (typeof WorkerGlobalScope !== "undefined" && self instanceof WorkerGlobalScope) ? self : window));
